Allow custom character for active dot
kenwheeler/slick pull request #4186
Opened 2022-05-02 19:30 UTC by rywall

I wanted to use an unfilled circle for inactive dots.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/7904/166312402-6e90c55f-d75d-4024-ac4e-6dc2266ce9b5.png">

2024-04-12 21:26 UTC, markvantilburg commented
@ahmadalfy Looks like a nice addition to me, but only includes the sass file and not the less/css file

2024-04-13 01:58 UTC, pablo67340 commented
@rywall 

Just as @markvantilburg mentions, excellent additions, would like to see the complete less/css versions, if you're unable to do this, I can PR into your fork prior. Let me know.

2024-04-13 02:00 UTC, pablo67340 requested changes
@rywall

Just as @markvantilburg mentions, excellent additions, would like to see the complete less/css versions, if you're unable to do this, I can PR into your fork prior. Let me know.

2024-04-15 03:59 UTC, rywall commented
@pablo67340 I added the less version. Hope this helps.

2024-08-30 20:16 UTC, markvantilburg approved these changes

2026-07-31 12:48 UTC, markvantilburg commented
@ahmadalfy can you merge this?

2026-08-01 15:56 UTC, ahmadalfy approved these changes

2026-08-01 15:56 UTC, ahmadalfy commented
This will be scheduled for the next release

2026-08-01 15:56 UTC, merged